"""Repository Protocol — abstract interface for data persistence.

Both InMemoryRepo (dev/test) and production managed PostgreSQL repositories
implement this protocol.
"""
from __future__ import annotations

from typing import Any, Dict, Iterable, List, Optional, Protocol, runtime_checkable

from .models import (
    ACLPolicy,
    Chunk,
    Document,
    IngestionJob,
    KnowledgeGeneration,
    PublicationOutboxEvent,
    Source,
    TableData,
)


@runtime_checkable
class Repo(Protocol):
    """Abstract repository interface used by retrieval and ingestion."""

    # ── Documents ──────────────────────────────────────────────────────
    def add_document(self, doc: Document) -> None: ...
    def get_document(self, doc_id: str) -> Optional[Document]: ...
    def list_documents(self, tenant_id: Optional[str] = None) -> List[Document]: ...
    def delete_documents(self, doc_ids: Iterable[str]) -> int: ...
    def delete_documents_by_source(self, source_id: str) -> List[str]: ...

    # ── Chunks ─────────────────────────────────────────────────────────
    def add_chunk(self, chunk: Chunk) -> None: ...
    def add_chunks(self, chunks: Iterable[Chunk]) -> int: ...
    def get_chunk(self, chunk_id: str) -> Optional[Chunk]: ...
    def list_chunks(self, doc_id: Optional[str] = None) -> List[Chunk]: ...
    def delete_chunks(self, chunk_ids: Iterable[str]) -> int: ...
    def delete_chunks_by_doc(self, doc_id: str) -> int: ...
    def iter_chunks(self) -> Iterable[Chunk]: ...

    # ── Staged generation publication ──────────────────────────────────
    def begin_knowledge_generation(self, generation: KnowledgeGeneration) -> None: ...
    def stage_knowledge_generation(
        self,
        generation_id: str,
        documents: Iterable[Document],
        chunks: Iterable[Chunk],
    ) -> Dict[str, int]: ...
    def mark_knowledge_generation_prepared(
        self,
        generation_id: str,
        stats: Optional[Dict[str, Any]] = None,
    ) -> None: ...
    def activate_knowledge_generation(
        self,
        source_id: str,
        generation_id: str,
        cleanup_point_ids: Iterable[str] = (),
        previous_doc_ids: Iterable[str] = (),
        expected_source_generation: Optional[str] = None,
    ) -> Optional[str]: ...
    def fail_knowledge_generation(
        self,
        generation_id: str,
        error: str,
        cleanup_point_ids: Iterable[str] = (),
    ) -> None: ...
    def get_active_generation_id(self, source_id: str) -> Optional[str]: ...
    def active_vector_points(self, chunk_ids: Iterable[str]) -> Dict[str, str]: ...

    # ── Publication outbox ─────────────────────────────────────────────
    def claim_publication_outbox(
        self,
        worker_id: str,
        lease_seconds: int = 120,
        limit: int = 10,
    ) -> List[PublicationOutboxEvent]: ...
    def complete_publication_outbox(self, outbox_id: int, worker_id: str) -> bool: ...
    def retry_publication_outbox(
        self,
        outbox_id: int,
        worker_id: str,
        error: str,
        delay_seconds: float,
        max_attempts: int = 10,
    ) -> bool: ...
    def reconcile_publication_outbox(self, max_attempts: int = 10) -> Dict[str, int]: ...

    # ── Policies ───────────────────────────────────────────────────────
    def add_policy(self, policy: ACLPolicy) -> None: ...
    def get_policy_hash(self, acl_policy_id: Optional[str] = None) -> Optional[str]: ...
    def list_policies(self, tenant_id: Optional[str] = None) -> List[ACLPolicy]: ...

    # ── Sources ────────────────────────────────────────────────────────
    def add_source(self, source: Source) -> None: ...
    def get_source(self, source_id: str) -> Optional[Source]: ...
    def list_sources(self, tenant_id: Optional[str] = None) -> List[Source]: ...
    def update_source(self, source_id: str, **kwargs: Any) -> Optional[Source]: ...
    def delete_source(self, source_id: str) -> bool: ...

    # ── Jobs ───────────────────────────────────────────────────────────
    def add_job(self, job: IngestionJob) -> None: ...
    def add_job_if_absent(self, job: IngestionJob) -> bool: ...
    def get_job(self, job_id: str) -> Optional[IngestionJob]: ...
    def list_jobs(self, tenant_id: Optional[str] = None, source_id: Optional[str] = None) -> List[IngestionJob]: ...
    def update_job(self, job_id: str, **kwargs: Any) -> Optional[IngestionJob]: ...
    def claim_next_job(self, worker_id: str, lease_seconds: int = 120, max_attempts: int = 3) -> Optional[IngestionJob]: ...
    def heartbeat_job(self, job_id: str, worker_id: str, lease_seconds: int = 120) -> bool: ...
    def release_job_lease(self, job_id: str, worker_id: str) -> bool: ...
    def reconcile_ingestion_jobs(self, max_attempts: int = 3) -> Dict[str, int]: ...

    # ── Tables (InMemory only; PostgresRepo is no-op) ──────────────────
    def register_table(self, table: TableData) -> None: ...
    def get_table(self, name: str) -> Optional[TableData]: ...

    # ── Runtime / debug ────────────────────────────────────────────────
    def healthcheck(self) -> bool: ...
    def export_state(self) -> Dict[str, List[dict]]: ...
