"""Repository Protocol — abstract interface for data persistence.

Both InMemoryRepo (dev/test) and PostgresRepo (production) implement this protocol.
"""
from __future__ import annotations

from typing import Any, Dict, Iterable, List, Optional, Protocol, runtime_checkable

from .models import ACLPolicy, Chunk, Document, IngestionJob, Source, TableData


@runtime_checkable
class Repo(Protocol):
    """Abstract repository interface used by retrieval and ingestion."""

    # ── Documents ──────────────────────────────────────────────────────
    def add_document(self, doc: Document) -> None: ...
    def get_document(self, doc_id: str) -> Optional[Document]: ...
    def list_documents(self, tenant_id: Optional[str] = None) -> List[Document]: ...
    def delete_documents(self, doc_ids: Iterable[str]) -> int: ...
    def delete_documents_by_source(self, source_id: str) -> List[str]: ...

    # ── Chunks ─────────────────────────────────────────────────────────
    def add_chunk(self, chunk: Chunk) -> None: ...
    def add_chunks(self, chunks: Iterable[Chunk]) -> int: ...
    def get_chunk(self, chunk_id: str) -> Optional[Chunk]: ...
    def list_chunks(self, doc_id: Optional[str] = None) -> List[Chunk]: ...
    def delete_chunks(self, chunk_ids: Iterable[str]) -> int: ...
    def delete_chunks_by_doc(self, doc_id: str) -> int: ...
    def iter_chunks(self) -> Iterable[Chunk]: ...

    # ── Policies ───────────────────────────────────────────────────────
    def add_policy(self, policy: ACLPolicy) -> None: ...
    def get_policy_hash(self, acl_policy_id: Optional[str] = None) -> Optional[str]: ...
    def list_policies(self, tenant_id: Optional[str] = None) -> List[ACLPolicy]: ...

    # ── Sources ────────────────────────────────────────────────────────
    def add_source(self, source: Source) -> None: ...
    def get_source(self, source_id: str) -> Optional[Source]: ...
    def list_sources(self, tenant_id: Optional[str] = None) -> List[Source]: ...
    def update_source(self, source_id: str, **kwargs: Any) -> Optional[Source]: ...
    def delete_source(self, source_id: str) -> bool: ...

    # ── Jobs ───────────────────────────────────────────────────────────
    def add_job(self, job: IngestionJob) -> None: ...
    def add_job_if_absent(self, job: IngestionJob) -> bool: ...
    def get_job(self, job_id: str) -> Optional[IngestionJob]: ...
    def list_jobs(self, tenant_id: Optional[str] = None, source_id: Optional[str] = None) -> List[IngestionJob]: ...
    def update_job(self, job_id: str, **kwargs: Any) -> Optional[IngestionJob]: ...
    def claim_next_job(self, worker_id: str, lease_seconds: int = 120, max_attempts: int = 3) -> Optional[IngestionJob]: ...
    def heartbeat_job(self, job_id: str, worker_id: str, lease_seconds: int = 120) -> bool: ...
    def release_job_lease(self, job_id: str, worker_id: str) -> bool: ...

    # ── Tables (InMemory only; PostgresRepo is no-op) ──────────────────
    def register_table(self, table: TableData) -> None: ...
    def get_table(self, name: str) -> Optional[TableData]: ...

    # ── Runtime / debug ────────────────────────────────────────────────
    def healthcheck(self) -> bool: ...
    def export_state(self) -> Dict[str, List[dict]]: ...
